### ISSUE TITLE
fix misinterpreting matthew 24

### ISSUE THREAD

**Issue by ArtskydJ** [ArtskydJ/josephdykstra.com#54]
apparently that post didn't get auto-added by my nifty travis-ci, and my guess is because it was a new post, and only exiting ones get updated? idk... fix it

**Comment by ArtskydJ** [comment]
fixed

**Comment by TehShrike** [comment]
Fixed in which commit? :-o

**Comment by TehShrike** [comment]
Looks like it was https://github.com/ArtskydJ/josephdykstra.com/commit/d0645e3d13899e2744c162a909e3e56a55a715f9

**Comment by ArtskydJ** [comment]
Actually https://github.com/ArtskydJ/josephdykstra.com/commit/bb7fa7d57f8968e6eae4dd676dca370d153d68d7.

I had to build it manually. I think my git command in travis doesn't pick up non-versioned files. (See #55)
